# Site settings
author: Lexi Mutia
title: Learner Lexi
header-img: img/home-bg.png
email: muse.malize@gmail.com
copyright_name: Lexi Mutia
description: > # this means to ignore newlines until "baseurl:"
  A informal documentation of my time with Flatiron School.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  leximutia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
